/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CorporaRouteImport } from './routes/corpora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocApiRouteImport } from './routes/doc.api'
import { Route as DocSplatRouteImport } from './routes/doc.$'
import { Route as CorporaCorpusIdRouteImport } from './routes/corpora_.$corpusId'
import { Route as CorporaCorpusIdTextIdRouteImport } from './routes/corpora_.$corpusId.$textId'

const CorporaRoute = CorporaRouteImport.update({
  id: '/corpora',
  path: '/corpora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocApiRoute = DocApiRouteImport.update({
  id: '/doc/api',
  path: '/doc/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocSplatRoute = DocSplatRouteImport.update({
  id: '/doc/$',
  path: '/doc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporaCorpusIdRoute = CorporaCorpusIdRouteImport.update({
  id: '/corpora_/$corpusId',
  path: '/corpora/$corpusId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporaCorpusIdTextIdRoute = CorporaCorpusIdTextIdRouteImport.update({
  id: '/$textId',
  path: '/$textId',
  getParentRoute: () => CorporaCorpusIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corpora': typeof CorporaRoute
  '/corpora/$corpusId': typeof CorporaCorpusIdRouteWithChildren
  '/doc/$': typeof DocSplatRoute
  '/doc/api': typeof DocApiRoute
  '/corpora/$corpusId/$textId': typeof CorporaCorpusIdTextIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corpora': typeof CorporaRoute
  '/corpora/$corpusId': typeof CorporaCorpusIdRouteWithChildren
  '/doc/$': typeof DocSplatRoute
  '/doc/api': typeof DocApiRoute
  '/corpora/$corpusId/$textId': typeof CorporaCorpusIdTextIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corpora': typeof CorporaRoute
  '/corpora_/$corpusId': typeof CorporaCorpusIdRouteWithChildren
  '/doc/$': typeof DocSplatRoute
  '/doc/api': typeof DocApiRoute
  '/corpora_/$corpusId/$textId': typeof CorporaCorpusIdTextIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corpora'
    | '/corpora/$corpusId'
    | '/doc/$'
    | '/doc/api'
    | '/corpora/$corpusId/$textId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corpora'
    | '/corpora/$corpusId'
    | '/doc/$'
    | '/doc/api'
    | '/corpora/$corpusId/$textId'
  id:
    | '__root__'
    | '/'
    | '/corpora'
    | '/corpora_/$corpusId'
    | '/doc/$'
    | '/doc/api'
    | '/corpora_/$corpusId/$textId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorporaRoute: typeof CorporaRoute
  CorporaCorpusIdRoute: typeof CorporaCorpusIdRouteWithChildren
  DocSplatRoute: typeof DocSplatRoute
  DocApiRoute: typeof DocApiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/corpora': {
      id: '/corpora'
      path: '/corpora'
      fullPath: '/corpora'
      preLoaderRoute: typeof CorporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/api': {
      id: '/doc/api'
      path: '/doc/api'
      fullPath: '/doc/api'
      preLoaderRoute: typeof DocApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$': {
      id: '/doc/$'
      path: '/doc/$'
      fullPath: '/doc/$'
      preLoaderRoute: typeof DocSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpora_/$corpusId': {
      id: '/corpora_/$corpusId'
      path: '/corpora/$corpusId'
      fullPath: '/corpora/$corpusId'
      preLoaderRoute: typeof CorporaCorpusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpora_/$corpusId/$textId': {
      id: '/corpora_/$corpusId/$textId'
      path: '/$textId'
      fullPath: '/corpora/$corpusId/$textId'
      preLoaderRoute: typeof CorporaCorpusIdTextIdRouteImport
      parentRoute: typeof CorporaCorpusIdRoute
    }
  }
}

interface CorporaCorpusIdRouteChildren {
  CorporaCorpusIdTextIdRoute: typeof CorporaCorpusIdTextIdRoute
}

const CorporaCorpusIdRouteChildren: CorporaCorpusIdRouteChildren = {
  CorporaCorpusIdTextIdRoute: CorporaCorpusIdTextIdRoute,
}

const CorporaCorpusIdRouteWithChildren = CorporaCorpusIdRoute._addFileChildren(
  CorporaCorpusIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorporaRoute: CorporaRoute,
  CorporaCorpusIdRoute: CorporaCorpusIdRouteWithChildren,
  DocSplatRoute: DocSplatRoute,
  DocApiRoute: DocApiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
