/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CorporaRouteImport } from './routes/corpora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocApiRouteImport } from './routes/doc.api'
import { Route as DocSplatRouteImport } from './routes/doc.$'
import { Route as CorporaCorpusIdRouteImport } from './routes/corpora_.$corpusId'
import { Route as CorporaCorpusIdTextIdRouteImport } from './routes/corpora_.$corpusId_.$textId'
import { Route as CorporaCorpusIdTextIdIndexRouteImport } from './routes/corpora_.$corpusId_.$textId.index'
import { Route as CorporaCorpusIdTextIdFulltextRouteImport } from './routes/corpora_.$corpusId_.$textId.fulltext'
import { Route as CorporaCorpusIdTextIdDownloadsRouteImport } from './routes/corpora_.$corpusId_.$textId.downloads'

const CorporaRoute = CorporaRouteImport.update({
  id: '/corpora',
  path: '/corpora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocApiRoute = DocApiRouteImport.update({
  id: '/doc/api',
  path: '/doc/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocSplatRoute = DocSplatRouteImport.update({
  id: '/doc/$',
  path: '/doc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporaCorpusIdRoute = CorporaCorpusIdRouteImport.update({
  id: '/corpora_/$corpusId',
  path: '/corpora/$corpusId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporaCorpusIdTextIdRoute = CorporaCorpusIdTextIdRouteImport.update({
  id: '/corpora_/$corpusId_/$textId',
  path: '/corpora/$corpusId/$textId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporaCorpusIdTextIdIndexRoute =
  CorporaCorpusIdTextIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CorporaCorpusIdTextIdRoute,
  } as any)
const CorporaCorpusIdTextIdFulltextRoute =
  CorporaCorpusIdTextIdFulltextRouteImport.update({
    id: '/fulltext',
    path: '/fulltext',
    getParentRoute: () => CorporaCorpusIdTextIdRoute,
  } as any)
const CorporaCorpusIdTextIdDownloadsRoute =
  CorporaCorpusIdTextIdDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => CorporaCorpusIdTextIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corpora': typeof CorporaRoute
  '/corpora/$corpusId': typeof CorporaCorpusIdRoute
  '/doc/$': typeof DocSplatRoute
  '/doc/api': typeof DocApiRoute
  '/corpora/$corpusId/$textId': typeof CorporaCorpusIdTextIdRouteWithChildren
  '/corpora/$corpusId/$textId/downloads': typeof CorporaCorpusIdTextIdDownloadsRoute
  '/corpora/$corpusId/$textId/fulltext': typeof CorporaCorpusIdTextIdFulltextRoute
  '/corpora/$corpusId/$textId/': typeof CorporaCorpusIdTextIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corpora': typeof CorporaRoute
  '/corpora/$corpusId': typeof CorporaCorpusIdRoute
  '/doc/$': typeof DocSplatRoute
  '/doc/api': typeof DocApiRoute
  '/corpora/$corpusId/$textId/downloads': typeof CorporaCorpusIdTextIdDownloadsRoute
  '/corpora/$corpusId/$textId/fulltext': typeof CorporaCorpusIdTextIdFulltextRoute
  '/corpora/$corpusId/$textId': typeof CorporaCorpusIdTextIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corpora': typeof CorporaRoute
  '/corpora_/$corpusId': typeof CorporaCorpusIdRoute
  '/doc/$': typeof DocSplatRoute
  '/doc/api': typeof DocApiRoute
  '/corpora_/$corpusId_/$textId': typeof CorporaCorpusIdTextIdRouteWithChildren
  '/corpora_/$corpusId_/$textId/downloads': typeof CorporaCorpusIdTextIdDownloadsRoute
  '/corpora_/$corpusId_/$textId/fulltext': typeof CorporaCorpusIdTextIdFulltextRoute
  '/corpora_/$corpusId_/$textId/': typeof CorporaCorpusIdTextIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corpora'
    | '/corpora/$corpusId'
    | '/doc/$'
    | '/doc/api'
    | '/corpora/$corpusId/$textId'
    | '/corpora/$corpusId/$textId/downloads'
    | '/corpora/$corpusId/$textId/fulltext'
    | '/corpora/$corpusId/$textId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corpora'
    | '/corpora/$corpusId'
    | '/doc/$'
    | '/doc/api'
    | '/corpora/$corpusId/$textId/downloads'
    | '/corpora/$corpusId/$textId/fulltext'
    | '/corpora/$corpusId/$textId'
  id:
    | '__root__'
    | '/'
    | '/corpora'
    | '/corpora_/$corpusId'
    | '/doc/$'
    | '/doc/api'
    | '/corpora_/$corpusId_/$textId'
    | '/corpora_/$corpusId_/$textId/downloads'
    | '/corpora_/$corpusId_/$textId/fulltext'
    | '/corpora_/$corpusId_/$textId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorporaRoute: typeof CorporaRoute
  CorporaCorpusIdRoute: typeof CorporaCorpusIdRoute
  DocSplatRoute: typeof DocSplatRoute
  DocApiRoute: typeof DocApiRoute
  CorporaCorpusIdTextIdRoute: typeof CorporaCorpusIdTextIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/corpora': {
      id: '/corpora'
      path: '/corpora'
      fullPath: '/corpora'
      preLoaderRoute: typeof CorporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/api': {
      id: '/doc/api'
      path: '/doc/api'
      fullPath: '/doc/api'
      preLoaderRoute: typeof DocApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$': {
      id: '/doc/$'
      path: '/doc/$'
      fullPath: '/doc/$'
      preLoaderRoute: typeof DocSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpora_/$corpusId': {
      id: '/corpora_/$corpusId'
      path: '/corpora/$corpusId'
      fullPath: '/corpora/$corpusId'
      preLoaderRoute: typeof CorporaCorpusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpora_/$corpusId_/$textId': {
      id: '/corpora_/$corpusId_/$textId'
      path: '/corpora/$corpusId/$textId'
      fullPath: '/corpora/$corpusId/$textId'
      preLoaderRoute: typeof CorporaCorpusIdTextIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpora_/$corpusId_/$textId/': {
      id: '/corpora_/$corpusId_/$textId/'
      path: '/'
      fullPath: '/corpora/$corpusId/$textId/'
      preLoaderRoute: typeof CorporaCorpusIdTextIdIndexRouteImport
      parentRoute: typeof CorporaCorpusIdTextIdRoute
    }
    '/corpora_/$corpusId_/$textId/fulltext': {
      id: '/corpora_/$corpusId_/$textId/fulltext'
      path: '/fulltext'
      fullPath: '/corpora/$corpusId/$textId/fulltext'
      preLoaderRoute: typeof CorporaCorpusIdTextIdFulltextRouteImport
      parentRoute: typeof CorporaCorpusIdTextIdRoute
    }
    '/corpora_/$corpusId_/$textId/downloads': {
      id: '/corpora_/$corpusId_/$textId/downloads'
      path: '/downloads'
      fullPath: '/corpora/$corpusId/$textId/downloads'
      preLoaderRoute: typeof CorporaCorpusIdTextIdDownloadsRouteImport
      parentRoute: typeof CorporaCorpusIdTextIdRoute
    }
  }
}

interface CorporaCorpusIdTextIdRouteChildren {
  CorporaCorpusIdTextIdDownloadsRoute: typeof CorporaCorpusIdTextIdDownloadsRoute
  CorporaCorpusIdTextIdFulltextRoute: typeof CorporaCorpusIdTextIdFulltextRoute
  CorporaCorpusIdTextIdIndexRoute: typeof CorporaCorpusIdTextIdIndexRoute
}

const CorporaCorpusIdTextIdRouteChildren: CorporaCorpusIdTextIdRouteChildren = {
  CorporaCorpusIdTextIdDownloadsRoute: CorporaCorpusIdTextIdDownloadsRoute,
  CorporaCorpusIdTextIdFulltextRoute: CorporaCorpusIdTextIdFulltextRoute,
  CorporaCorpusIdTextIdIndexRoute: CorporaCorpusIdTextIdIndexRoute,
}

const CorporaCorpusIdTextIdRouteWithChildren =
  CorporaCorpusIdTextIdRoute._addFileChildren(
    CorporaCorpusIdTextIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorporaRoute: CorporaRoute,
  CorporaCorpusIdRoute: CorporaCorpusIdRoute,
  DocSplatRoute: DocSplatRoute,
  DocApiRoute: DocApiRoute,
  CorporaCorpusIdTextIdRoute: CorporaCorpusIdTextIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
