name: Deploy to staging

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  staging:
    uses: clscor-io/eltec-frontend/.github/workflows/deployment.yml@main
    with:
      host: staging.eltec.clscor.io
      deploy-path: /var/www/html
    secrets:
      deploy-key: ${{ secrets.CLSCOR_DEPLOY_KEY }}
      deploy-user: ${{ secrets.CLSCOR_DEPLOY_USER }}
